### ISSUE TITLE
Won't compile under MSVC 2017 preview

### ISSUE THREAD

**Issue by migdalskiy** [lexxmark/winflexbison#10]
MSVC 2017 compiler errors out on negating an unsigned in location.cc:80

-static_cast<unsigned int>(rhs)

All that's needed to get it to compile is to change it to 

static_cast<unsigned int>(-rhs)

It's better to negate the int, then cast to unsigned rather than cast to unsigned, then negate

**Comment by lexxmark** [comment]
Fixed. Please check.
