### ISSUE TITLE
virus scanner complains

### ISSUE THREAD

**Issue by bitsrules** [lexxmark/winflexbison#11]
I have an issue meaning I can't install flex on our build server because the virus scanner freaks out.
I ran the check on but the prebuild binaries and my own compiled version using this virus scanner
[https://www.virustotal.com/#/home/upload](https://www.virustotal.com/#/home/upload)

```
ALYac                                   Gen:Variant.Graftor.419163
Arcabit                                 Trojan.Graftor.D6655B
Cybereason                          malicious.1b8fb7
F-Secure                               Gen:Variant.Graftor.419163
```

**Comment by lexxmark** [comment]
Sorry for delay,

I faced the same problem when migrated to Visual Studio 2017. May be it's connected.
I've just marked win_flex.exe as false positive.
If you know how to fix it, let me know.

Regards,
   Alex

**Comment by sg495** [comment]
I have scanned different versions.it would seem that the issue started with your "update readme" commit 3232d5c on 5/12/2017 8.21. My  gives no problem on previous versions

**Comment by sg495** [comment]
I have scanned different versions, and I'm going to paste here a short summary.

Both Windows Defender and VirusTotal think that the win_flex issue started with your "update readme" commit 3232d5c on 5/12/2017 8.21, with WD reporting Trojan:Win32/Azden.A!cl and 6/68 engines in Virus Total reporting issues (with different levels of confidence). 

Before that, WD sees no issues, and only 2/68 engines in VirusTotal see generic issues. WD sees no issues with the latest version of win_bison, while 2/68 engines in VirusTotal see issues starting way back, with Baidu reporting Win32.Trojan.WisdomEyes.

**Comment by lexxmark** [comment]
Thank you for such a detailed report.

The problem raised once I've migrated to VS 2017. I think I should revert to VS 2015 for now to get rid of virus issues. 

I will do it in near weeks. I will let you know when I'm done, please check and report here the virus scan results.

**Comment by lexxmark** [comment]
I have updated [win_flex_bison ](https://sourceforge.net/projects/winflexbison/files)(reverted to VS 2015).
Please check new files and report an issue if virus scanners still detects something.
