### ISSUE TITLE
Make github release with CMakeLists.txt included

### ISSUE THREAD

**Issue by solvingj** [lexxmark/winflexbison#12]
Hey there, just a request for an official github release with the CMakeLists.txt included. We prefer to pull sources only from github releases.

**Comment by lexxmark** [comment]
[v2.4.12](https://github.com/lexxmark/winflexbison/releases/tag/v2.4.12) - has bison 2.7
[v2.5.14](https://github.com/lexxmark/winflexbison/releases/tag/v2.5.14) - has bison 3.0
