### ISSUE TITLE
include the documentation for creating VS-build rules in source

### ISSUE THREAD

**Issue by GitMensch** [lexxmark/winflexbison#15]
Do you accept a PR of converting http://sourceforge.net/p/winflexbison/wiki/Visual%20Studio%20custom%20build%20rules/ to MD format and place it in the source tree (maybe in a new subdirectory doc-VS-build-rules)?

If the answer is "yes" can we combine this with https://readthedocs.org/ for nice viewing in different formats, easier editing and to requests pull-requests for edits?

**Comment by lexxmark** [comment]
sure for both questions

**Comment by GitMensch** [comment]
@lexxmark - I actually see that there is not much to convert as the SF wiki pages use Markdown formatting already. It doesn't make sense to copy-and-edit the existing content just to get the same result...

Please either copy the source of the existing page here or add me there as a developer allowing me to click the "edit" button to get it myself.

I'll add a PR for including this (if you don't have another preference into new subdirectory `doc-VS-build-rules) afterwards.

**Comment by lexxmark** [comment]
I appreciate your help. Sorry for not involving in this activity, currently I'm concentrated on refactoring in  QtnProperty project.
I have attached files you requested here. Is it enough or I missed something?
![1](https://user-images.githubusercontent.com/6108224/40167146-1d4fdb40-5975-11e8-979b-7f44b979c61e.png)
![2](https://user-images.githubusercontent.com/6108224/40167148-1d685288-5975-11e8-9804-8b49abd667a1.png)
![3](https://user-images.githubusercontent.com/6108224/40167149-1d81a742-5975-11e8-9393-6486dab1233e.png)
![4](https://user-images.githubusercontent.com/6108224/40167150-1d9dfffa-5975-11e8-9907-b74cc07ef731.png)
![5](https://user-images.githubusercontent.com/6108224/40167151-1db4ae4e-5975-11e8-92d1-83ec9139c8e3.png)
![6](https://user-images.githubusercontent.com/6108224/40167153-1dded02a-5975-11e8-8fba-c1faed37a0b0.png)
![bisonproperties](https://user-images.githubusercontent.com/6108224/40167154-1df7393a-5975-11e8-93ee-dbeb2b4b5883.png)
![flex_debuging](https://user-images.githubusercontent.com/6108224/40167155-1e15433a-5975-11e8-98d7-1d3b63d8bba3.png)
![flexproperties](https://user-images.githubusercontent.com/6108224/40167157-1e34d498-5975-11e8-9de7-c13c109ce6d7.png)
![properties](https://user-images.githubusercontent.com/6108224/40167158-1e57bb7a-5975-11e8-8e2c-279f2a3be553.png)
![verbosity](https://user-images.githubusercontent.com/6108224/40167159-1e7be75c-5975-11e8-900f-16148c7a083f.png)
[VisualStudioCustomBuildRules.txt](https://github.com/lexxmark/winflexbison/files/2012400/VisualStudioCustomBuildRules.txt)

**Comment by GitMensch** [comment]
@lexxmark 
> I have attached files you requested here. Is it enough or I missed something?

It is fine.

**Comment by GitMensch** [comment]
I'll redo the PR tomorrow (contains errors...)
