### ISSUE TITLE
Update to bison 3.0.5

### ISSUE THREAD

**Issue by pal1000** [lexxmark/winflexbison#20]

**Comment by GitMensch** [comment]
Note: See [Bison 3.0.5 Announcement](https://savannah.gnu.org/forum/forum.php?forum_id=9165), dated Mon 28 May 2018 07:04:13 AM CEST.

Side note: next flex release is expected "soon".

**Comment by lexxmark** [comment]
[winflexbison_bison_3_0_5.zip](https://github.com/lexxmark/winflexbison/files/2224898/winflexbison_bison_3_0_5.zip)
Please try this updated win_bison package and revert back if there are issues or everything ok.
I will test it a couple of days.

**Comment by pal1000** [comment]
I'll test it myself soon. I build Mesa3D as part of [pal1000/mesa-dist-win](https://github.com/pal1000/mesa-dist-win) project and there is release 18.1.5 planned for this weekend.

**Comment by pal1000** [comment]
Done Mesa3D 18.1.5 builds and I had no problems with Bison 3.0.5.
