### ISSUE TITLE
Bison 3.1 has been released

### ISSUE THREAD

**Issue by donmac703** [lexxmark/winflexbison#22]
See announcement at [https://savannah.gnu.org/forum/forum.php?forum_id=9225] (dated Tue 28 Aug 2018 04:28:44 AM UTC)

**Comment by donmac703** [comment]
Hi,  Looks like there is a lot of activity going on to bring the generated scanner up to Modern C++ principles.  Depending on effort involved on your side, it may be better to wait a little.  See https://github.com/akimd/bison for latest commits.

While I am very interested in the Typed Mid-rule actions introduced in Bison 3.1, I am also using the generated scanner in a C++17 target...

**Comment by GitMensch** [comment]
@donmac703 The 3.1 is the latest release and contains both bug-fixes and new features. I have no idea why we should wait and don't think an inofficial bison fork at Github provides any reasons to do so.

**Comment by lexxmark** [comment]
upgrading win_bison is not a big deal (in comparing with win_flex).
just need some free time to do this. :)

**Comment by lexxmark** [comment]
@donmac703 
Please try this out. I will test it a bit as well.
[winflexbison.zip](https://github.com/lexxmark/winflexbison/files/2378480/winflexbison.zip)

**Comment by GitMensch** [comment]
@lexxmark :-) Wouldn't it be reasonable to push your changes to master and point donmac703 to the CI-build?

**Comment by Croydon** [comment]
When it's experimental than better another branch as master :)

**Comment by GitMensch** [comment]
Correct, @lexxmark feel it is experimental it would be good to create a short-term 3.1 branch, do it there, point others to the created artifacts (thanks to #27 comparable with full releases).

**Comment by GitMensch** [comment]
What do we see now?

https://github.com/lexxmark/winflexbison/tree/bison3.1
with binaries at https://ci.appveyor.com/project/lexxmark/winflexbison

**Comment by lexxmark** [comment]
I'm pushing bison3.1 branch with upgraded bison code

**Comment by lexxmark** [comment]
There is a new branch bison3.1
appveyor is passed [https://ci.appveyor.com/project/lexxmark/winflexbison/build/1.0.18](https://ci.appveyor.com/project/lexxmark/winflexbison/build/1.0.18)

**Comment by GitMensch** [comment]
Is there any time schedule for integrating the branch into master?

**Comment by donmac703** [comment]
Hi,
The provided zip file has errors when run against my 7.5K line grammar file, which previously was without errors.
It flags lines such as:

%define api.token.constructor
%define api.value.type variant

with error: %define variable 'api.token.constructor' redefined

commenting out the lines that get this redefined error will lead to error C000 0409.

This can be reproduced by using the variant.yy provided in the examples folder of the Bison 3.1 distro.

**Comment by lexxmark** [comment]
Ok, will look into it.

**Comment by donmac703** [comment]
Hi,
Thanks for the quick response.
I can confirm that I am now getting the expected summary results.

**Comment by GitMensch** [comment]
@donmac703 I was partly wrong with the "inofficial bison fork at GitHub": it very likely is from the Bison main developer (even if not up-to-date with the official repo found at http://git.savannah.gnu.org/cgit/bison.git) I still think it is reasonable to get version 3.1 into win_bison soon.

**Comment by lexxmark** [comment]
> That looks not bad, I guess the extra " is an error in win_bison?

Have you tested the last bison3.1 artifact [win_flex_bison-dev-2017-Win32-Release.zip](https://ci.appveyor.com/api/buildjobs/d0tq2fb8a3j6ynao/artifacts/build%2Fwin_flex_bison-dev-2017-Win32-Release.zip)?
I have experienced this problem because had "/data" folder outdated (it remained from master). 

> After the examples are built the real testsuite follows but all but the skipped tests fail because win_bison doesn't use binary mode for output and the output is verified.

I've changed fopen mode from "w"/"w+" to "wb"/"wb+" and it seems output files with unix line endings now. Please check. Note that "b" mode is non standard.

If users will complain about line-endings we will think of WINFLEXBISON_UNIX_LF solution.

**Comment by GitMensch** [comment]
Something got broken on the way, that's the current output from the examples:

~~~
=====================================
   GNU Bison 3.1: ./test-suite.log
=====================================

# TOTAL: 4
# PASS:  2
# SKIP:  0
# XFAIL: 0
# FAIL:  2
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: examples/variant
======================

Assertion failed: yytypeid_, file examples/variant.hh, line 196
variant: FAIL: 1 (expected status: 0, effective: 3)
FAIL examples/variant.test (exit status: 1)

FAIL: examples/calc++/calc++
============================

--(end of buffer or a NUL)
--accepting rule at line 59 ("toto")
--accepting rule at line 40 (" ")
--accepting rule at line 49 (":=")
--accepting rule at line 40 (" ")
--accepting rule at line 51 ("1")
Assertion failed: yytypeid_, file examples/calc++/parser.hh, line 195
calc++: FAIL: 1 (expected status: 0, effective: 3)
Assertion failed: yytypeid_, file examples/calc++/parser.hh, line 195
calc++: FAIL: 2 (expected status: 0, effective: 3)
Starting parse
Entering state 0
Reducing stack by rule 2 (line 49):
-> $$ = nterm assignments (1.1: )
Stack now 0
Entering state 2
Reading a token: Next token is token "identifier" (-:1.1: a)
Shifting token "identifier" (-:1.1: a)
Entering state 5
Reading a token: Next token is token ":=" (-:1.3-4: )
Shifting token ":=" (-:1.3-4: )
Entering state 11
Reading a token: Assertion failed: yytypeid_, file examples/calc++/parser.hh, line 195
calc++: FAIL: 3 (expected status: 0, effective: 3)
Assertion failed: yytypeid_, file examples/calc++/parser.hh, line 195
calc++: FAIL: 4 (expected status: 0, effective: 3)
Assertion failed: yytypeid_, file examples/calc++/parser.hh, line 195
calc++: FAIL: 5 (expected status: 1, effective: 3)
FAIL examples/calc++/calc++.test (exit status: 1)
~~~

The other tests got better, but many are still failing. The ones I've tested mainly for EOL in stdout/stderr - did you fix this, too? Example of the test failure:

~~~

**Comment by lexxmark** [comment]
> Something got broken on the way, that's the current output from the examples:
Assertion failed: yytypeid_, file examples/variant.hh, line 196
Assertion failed: yytypeid_, file examples/calc++/parser.hh, line 195

Could you please give me "examples/variant.hh" and "examples/calc++/parser.hh" files to see asserting code.

> The other tests got better, but many are still failing. The ones I've tested mainly for EOL in stdout/stderr - did you fix this, too?

Do you still have EOL mismatch errors? Please give me an example to reproduce.

> -input-c.y:1.7: error: %code qualifier 'q' is not used

Have you ensured that tests are compatible with win_bison 3.1
Please give me steps to reproduce.

> Note: Those failures are also seen when building with MinGW-GCC.
Can you please add a configurable switch **for this** both in flex and bison) as I'd like to suggest this as a patch upstream.

For what? Wrap my changes about "wb+"/"wb" modes with some macro?

**Comment by lexxmark** [comment]
I've released bison 3.1

**Comment by Croydon** [comment]
And this allowed me to remove the patches from the Conan recipe, awesome :)

https://github.com/bincrafters/conan-winflexbison/commit/8fcce2addf0fe96864fe9d93c16c550c140284ff

https://bintray.com/bincrafters/public-conan/winflexbison%3Abincrafters

![winflexbison](https://user-images.githubusercontent.com/1593194/46215243-2e2e2e80-c33d-11e8-9396-d392e480e689.PNG)

**Comment by GitMensch** [comment]
@Croydon - completely unrelated to the issue but the bintray package misses description, license, website, VCS, issue tracker, README, Release Notes...

You may use the update for winflexbison to add those information :-)

**Comment by donmac703** [comment]
Closing an issue for a previous release that Alex built  for the community and was successfully used.
