### ISSUE TITLE
register keyword used in the generated lexer

### ISSUE THREAD

**Issue by khaledmohammed** [lexxmark/winflexbison#3]
register keyword used in the generated lexer such as the following:
	register yy_size_t number_to_move = (yy_n_chars) + 2;

c++11 has deprecated the "register" keyword. register keyword is a hint to the compiler.

It would be nice if we can remove the "register" keyword from the generated scanner for at least c++, if not  for c. 

Some compilers have started printing a warning message if c++11x option is choosen to compile the scanner, and causes issue in the build system

Thanks,
-Khaled

**Comment by lexxmark** [comment]
Ok, will look into it

**Comment by lexxmark** [comment]
Sorry for delay, I was sick a little. I will try to upgrade win_flex to version 2.6.3
Seems there is no any **register** words in the generated code.
Will it works for you? Or do you depend on 2.5.37 version?

**Comment by khaledmohammed** [comment]
Hi Alex,

Thank you so much. Upgrading to 2.6.3 will be wonderful.

Thanks again,
-khaled

**Comment by lexxmark** [comment]
Hi Khaled,

just finished upgrading win_flex, now testing it.
Could you please take a new version from releses section [here](https://github.com/lexxmark/winflexbison/releases/download/v.2.5.7/win_flex_bison-2.5.7.zip) and try it.
And let me know in case any issues.

Regards,
   Alex

**Comment by khaledmohammed** [comment]
Thank you. I did not get a chance to try it, but I will. Thanks :)

**Comment by lexxmark** [comment]
You are welcome.
I've released flex 2.6.3 so you can get it from http://sourceforge.net/projects/winflexbison/
