### ISSUE TITLE
Bison 3.3.2 has been released

### ISSUE THREAD

**Issue by pal1000** [lexxmark/winflexbison#33]
Announcement: http://lists.gnu.org/archive/html/bison-announce/2019-02/msg00000.html
This has only a single fix so porting it should much easier.

**Comment by lexxmark** [comment]
Here is a new version [win_bison-3.3.2.zip](https://github.com/lexxmark/winflexbison/files/2903834/win_bison-3.3.2.zip)

Can you check that the fix is working here?

**Comment by GitMensch** [comment]
If we'd be able to run the testsuite that is shipped with bison (ideally with CI) then we'd know the answer.

Just to ping on this...

**Comment by pal1000** [comment]
At least it doesn't break what Mesa3D graphics library uses on windows. Unfortunately I don't have a testcase for 3.3.2 fix. So I am pretty much pushed to the sidelines.

**Comment by lexxmark** [comment]
That's pity we don't have a test case for this release. I will commit changes under bison3.3.2 branch and wait until someone really need this version to publish it.

**Comment by GitMensch** [comment]
https://github.com/lexxmark/winflexbison/releases/tag/v2.5.18
