### ISSUE TITLE
Bison gives error data/skeletons/yacc.c:1652: undefined macro `b4_symbol(114, has_type)'

### ISSUE THREAD

**Issue by LmTinyToon** [lexxmark/winflexbison#35]
I am trying to use bison, but it gives error data/skeletons/yacc.c:1652: undefined macro `b4_symbol(114, has_type)'. bison from cygwin works fine.

NOTE: I found out that such error is followed with warnings
warning : 1 nonterminal useless in grammar [-Wother]
warning : 1 rule useless in grammar [-Wother]

**Comment by lexxmark** [comment]
Hi Alexander,

Which version are you using?
Please give me *.y file and batch command to reproduce.

**Comment by LmTinyToon** [comment]
@lexxmark , I am sorry for late. I have no copy of grammar file (it was hugely increased and rewritten). I fixed it few days ago, main reason was in my typo in grammar file. After this bug fix win bison works fine. Unfortunately I don't remember exact type of expression typo which caused bug. Anyway it works fine now. Thanks for reply.
