### ISSUE TITLE
--header-file option in the latest win_flex

### ISSUE THREAD

**Issue by a-kakuto** [lexxmark/winflexbison#4]
Does the --header-file option in the win_flex in
win_flex_bison-2.5.8.zip work?
I have tested
win_flex -o f-l.c --header-file=f-l.h gabc-score-determination.l
by using a source in gregorio-5.0.0-beta1.
The header file f-l.h is not generated.
In the case of the win_flex in win_flex_bison-2.5.6.zip,
both of f-l.c and f-l.h were generated.

**Comment by lexxmark** [comment]
OK, will check it

**Comment by lexxmark** [comment]
I've fixed this regression. Please check

**Comment by a-kakuto** [comment]
Confirmed!  Thanks very much.
