### ISSUE TITLE
Can we delete 3.x branches?

### ISSUE THREAD

**Issue by GitMensch** [lexxmark/winflexbison#41]
Just asking @lexxmark before doing so.
This would leave us with master, the 2.7 branch and development (which includes adjustments added for running the tests [I'll likely not come to this in the next weeks but still plan to do that "someday"]).

**Comment by lexxmark** [comment]
I agree, we could remove those branches.
Any version could be checkouted by tag.

I need to say I will have a very limited access to github next 2 months due to summer vacations.

**Comment by GitMensch** [comment]
Done.
