### ISSUE TITLE
Is it possible to change table construction in bison?

### ISSUE THREAD

**Issue by LmTinyToon** [lexxmark/winflexbison#44]
Is it possible to change table construction (for example via%define lr.type )?

**Comment by lexxmark** [comment]
I had never tried this. win_bison should work like regular bison. Everything that worked in gnu bison should work with win_bison as well.

**Comment by GitMensch** [comment]
Please see the [Bison manual](https://www.gnu.org/software/bison/manual/html_node/LR-Table-Construction.html) about possibilities to tweak the table construction.
