### ISSUE TITLE
win_bison can't find data directory unless it's in the current directory

### ISSUE THREAD

**Issue by nirbheek** [lexxmark/winflexbison#48]
Starting with 2.5.19, if the `data/` directory isn't in the current directory, running win_bison gives the following error: `data/m4sugar/m4sugar.m4: cannot open: No such file or directory`

Looking at the git history, this broke while merging the upstream changes. `bison/src/main.c` doesn't use `get_local_pkgdatadir()` anymore, which had been patched to use `get_app_path()` from `common/misc/app_path.c`. Instead, the datadir is fetched by calling `pkgdatadir()` in `bison/src/files.c`. So, that function needs to be changed to call `get_app_path()` and return that path.

**Comment by lexxmark** [comment]
Thank you for discovering this bug. Going to fix it soon.

**Comment by pal1000** [comment]
I was able to hit it too when building Mesa3D with MSVC.

**Comment by lexxmark** [comment]
Try this binary. If it works I'll publish it.
[win_flex_bison-2.5.20.zip](https://github.com/lexxmark/winflexbison/files/3624500/win_flex_bison-2.5.20.zip)

**Comment by nirbheek** [comment]
I tested it and it works great, thanks!

**Comment by pal1000** [comment]
I worked for me too.
