### ISSUE TITLE
Update bison to 3.6.4

### ISSUE THREAD

**Issue by GitMensch** [lexxmark/winflexbison#56]
Bison [3.6 announcement](https://savannah.gnu.org/forum/forum.php?forum_id=9735)

>- the developer can forge syntax error messages the way she wants.
>- token string aliases can be internationalized, and UTF-8 sequences are properly preserved.
>- push parsers can ask at any moment for the list of "expected tokens", which can be used to provide syntax-driven autocompletion.
>- yylex may now tell the parser to enter error-recovery without issuing an error message (when the error was already reported by the scanner).

[Git log](https://git.savannah.gnu.org/cgit/bison.git/log/?h=v3.6.4) and [ftp](http://ftp.gnu.org/gnu/bison/?C=M;O=D) shows that 3.6.4 is the current release.

**Comment by lexxmark** [comment]
Will take care of it after vacation at the end of July

**Comment by lexxmark** [comment]
I have updated win_bison to v3.7.1 please test binaries [win_flex_bison-2.5.23.zip](https://github.com/lexxmark/winflexbison/files/5121613/win_flex_bison-2.5.23.zip).

I pushed changes in master branch and built it using VS2019.

Will update CMake stuff in a week. @GitMensch if you have a chance to verify and fix existing CMake and create VS2019 build target I will really appreciate it.

**Comment by GitMensch** [comment]
>  if you have a chance to verify and fix existing CMake

only hardly, I try to not use CMake when it isn't necessary and dislike if I have to

> and create VS2019 build target

In CMake or a plain VS sln? The later should be possible, if needed.

**Comment by GitMensch** [comment]
[Bison 3.7](https://savannah.gnu.org/forum/forum.php?forum_id=9785) is really cool Haven't seen that before - thank you.
So did we get any further with the coloring? This would obviously be useful for 3.7, too.

**Comment by lexxmark** [comment]
> only hardly, I try to not use CMake when it isn't necessary and dislike if I have to

Ok, don't mind I will update CMake.

> In CMake or a plain VS sln? The later should be possible, if needed.

I have created VS2019 folder with sln file there.

> So did we get any further with the coloring? This would obviously be useful for 3.7, too.

No, I only adopted new code.

Also I had to simplify unicode support introduced in 3.7.1 (see [unicodeio.c](https://github.com/lexxmark/winflexbison/blob/master/common/m4/lib/unicodeio.c) ). For example instead of Unicode 'dot' symbol it uses fallback "*" character. 

To fix this I need some example that uses this code (I guess it's some calling argument). I didn't dig into this.

**Comment by lexxmark** [comment]
Just looked at v3.7 release notes and saw '-Wcounterexamples' option that uses unicode symbols. I think it makes sense to fix  "unicodeio.c" file.

**Comment by lexxmark** [comment]
> Just looked at v3.7 release notes and saw '-Wcounterexamples' option that uses unicode symbols. I think it makes sense to fix "unicodeio.c" file.

After some investigation it seems very hard to output multibyte strings in windows console.
Will leave it as it is.
Any ideas/help are welcome.

![image](https://user-images.githubusercontent.com/6108224/91409063-b81cf580-e7f9-11ea-8dbf-46ffc6b3416a.png)
vs
![image](https://user-images.githubusercontent.com/6108224/91409148-db47a500-e7f9-11ea-976a-99bb90e5662e.png)

**Comment by GitMensch** [comment]
> After some investigation it seems very hard to output multibyte strings in windows console.

That wouldn't be reasonable as the windows console has a long history of bad and partial broken support for that. The only "target" for that would be a redirection of stderr to a file.

> Will leave it as it is.

If that is about the

       `.>

instead of the single multibyte character: that would be fine as-is.
But if someone uses an encoding with multibyte chars in the source file (UTF-8, UTF-16 or others) for the tokens, like

~~~
%token UMLAUT_AE		"Ä"
%token UMLAUT_UE		"Ü"
~~~

then this should be preserved in the generated source.

**Comment by lexxmark** [comment]
> But if someone uses an encoding with multibyte chars in the source file (UTF-8, UTF-16 or others) for the tokens, like

I don't remember any other issues while adopting new bison version.

Can you check that mulibyte tokens are supported now or do you have some example *.y file to try?

**Comment by lexxmark** [comment]
A new release has been published [v2.5.23](https://github.com/lexxmark/winflexbison/releases/tag/v2.5.23)
Also new version has been pushed as a chocolatey package [v2.5.23.20200829](https://chocolatey.org/packages/winflexbison3/2.5.23.20200829).

**Comment by lexxmark** [comment]
Consider this issue as done.
