### ISSUE TITLE
Bison-3.7.2

### ISSUE THREAD

**Issue by GitMensch** [lexxmark/winflexbison#60]
> GNU Bison NEWS
> 
> * Noteworthy changes in release 3.7.2 (2020-09-05) [stable]
> 
>   This release of Bison fixes all known bugs reported for Bison in MITRE's
>   Common Vulnerabilities and Exposures (CVE) system.  These vulnerabilities
>   are only about bison-the-program itself, not the generated code.

Would there be a win-bison update incorporating these changes any time soon?

_Originally posted by @a11apurva in https://github.com/lexxmark/winflexbison/issues/58#issuecomment-690350988_

**Comment by lexxmark** [comment]
we should close it once release bison v3.7.4

**Comment by GitMensch** [comment]
Superseded by #68
