### ISSUE TITLE
v2.5.23 not working on Windows XP

### ISSUE THREAD

**Issue by a11apurva** [lexxmark/winflexbison#61]
We migrated our entire project to v2.5.23 (Bison-3.7.1) and everything worked wonderfully on Windows 10. However today when I tried on windows-XP I am getting the following error - `bison: cannot execute: %1 is not a valid Win32 application.`

Win 10 -

```
$ bison.exe --version
bison (GNU Bison) 3.7.1
Written by Robert Corbett and Richard Stallman.
```
Win XP -
```
$ bison.exe --version
bison: cannot execute: %1 is not a valid Win32 application.

```
Can you please help? I was able to build my project on XP using the Bison executable for Bison-2.4

edit - 
```
$ file bison.exe
bison.exe:      extended DOS executable (.EXE) -- Win32 or NT Portable format
```

**Comment by GitMensch** [comment]
Does it work with the current vs2015 artifact?
https://ci.appveyor.com/api/buildjobs/vg8v8c5ao4urbjqj/artifacts/build%2Fwin_flex_bison-dev-2015-Win32-Release.zip

**Comment by a11apurva** [comment]
@GitMensch, I tried, but unfortunately it is threw the same error with this too.

**Comment by lexxmark** [comment]
As I remember under VS2015 we should explicitly enable XP support in project settings. I believe VS2019 doesn't support XP anymore.

You can try to build bison source code using VS2015 with proper settings but it might not compile because of outdated С++ compiler.

**Comment by GitMensch** [comment]
I think we should set the cmake up to let the VC2015 environment use the -xp toolset.
This way we can provide it (as long as VS2015 builds it the -xp toolset should do the same; and VC2015 is also the minimal version for the gnulib parts that handle VC, so it should be fine).

**Comment by lexxmark** [comment]
I don't have VS2015 to test it.
@GitMensch Could you test it?
There is definition of the build flag needed to support XP in VS2015 https://stackoverflow.com/questions/35664861/how-to-target-windows-xp-in-microsoft-visual-studio-c/35666906

**Comment by lexxmark** [comment]
I have added XP support to appveyor script. The following artifact should support XP
https://ci.appveyor.com/api/buildjobs/ri8fcm5b4c0qgc68/artifacts/build%2Fwin_flex_bison-dev-2015-Win32-Release.zip

@a11apurva Please verify.

**Comment by a11apurva** [comment]
Hi @lexxmark, works as expected. 

```
$ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft Windows 7 Enterprise
OS Version:                6.1.7601 Service Pack 1 Build 7601

$ bison --version
bison (GNU Bison) 3.7.1
Written by Robert Corbett and Richard Stallman.

Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```
Thanks a lot! Closing the issue.

**Comment by GitMensch** [comment]
Hm, I think one last piece is missing:

* potentially make a release that includes the Appveyor created XP version
* document "somewhere" which version to use on XP

@lexxmark what do you think?

**Comment by lexxmark** [comment]
> Hm, I think one last piece is missing:

Yes that makes sense.

> OS Name:                   Microsoft Windows 7 Enterprise

@a11apurva  why did you test on Windows7 system and not WindowsXP?

**Comment by a11apurva** [comment]
> @a11apurva why did you test on Windows7 system and not WindowsXP?

That was such a blunder. Apologies. 

Same error on XP still - 

```
$ systeminfo | findstr /B /C:"OS Name" /C:"OS Version"
OS Name:                   Microsoft(R) Windows(R) XP Professional x64 Edition
OS Version:                5.2.3790 Service Pack 2 Build 3790
$ bison --version
bison: cannot execute: %1 is not a valid Win32 application.
```

**Comment by GitMensch** [comment]
Please directly `cd` to the place where the archive was extracted and use `win_bison.exe --version` - same message?

**Comment by a11apurva** [comment]
Tried it on another XP system -

<img width="720" alt="winBison1" src="https://user-images.githubusercontent.com/17289080/100326277-c1cc1a00-2fef-11eb-8b2a-a7a15f07ca31.PNG">

**Comment by GitMensch** [comment]
@lexxmark You set the VC var PLATFORMTOOLSET, but this is only honored by msbuild. My _guess_ is that [CMAKE_VS_PLATFORM_TOOLSET](https://cmake.org/cmake/help/latest/variable/CMAKE_VS_PLATFORM_TOOLSET.html) should be set from this variable.

**Comment by lexxmark** [comment]
> You set the VC var PLATFORMTOOLSET, but this is only honored by msbuild. My guess is that CMAKE_VS_PLATFORM_TOOLSET should be set from this variable.

Can you try this?

**Comment by lexxmark** [comment]
@a11apurva Please verify that package https://ci.appveyor.com/api/buildjobs/s1nbkybjat8ysfiv/artifacts/build%2Fwin_flex_bison-dev-2015-Win32-Release.zip

**Comment by a11apurva** [comment]
I haven't tested on XP yet as the machine is down, but it says Bison 3.7.4, is this the correct package?

**Comment by lexxmark** [comment]
yes, that's correct. I'm migrating to bison 3.7.4 if it works we can rollup windows XP fix for any version we need.

**Comment by a11apurva** [comment]
I am afraid, still not working on XP - 

![image](https://user-images.githubusercontent.com/17289080/102452172-ed2aad80-405f-11eb-945f-14cea1c43be2.png)

**Comment by lexxmark** [comment]
It seems I have to manage to enforce Visual Studio to build project with v140_xp toolset.

The only problem still is that appveyor don't supply VS with such a toolset. Have to dig further.

**Comment by a11apurva** [comment]
We have moved all our systems to win10.

If there are no other takers for the Bison with XP support then you guys can park this for now.

**Comment by lexxmark** [comment]
OK, I'm going to remove VS2015 support and all XP stuff then.

I think VS2017/VS2019 support would be enough.

**Comment by GitMensch** [comment]
I initially was thinking that this is a bad idea, but came to the conclusion that this is fine - people can use an older version for old parsers. The question is: what is the latest release that actually _has_ XP support? Maybe we can hand-craft a version and attach it to one of the releases, adding a release note "last with XP support"?

**Comment by lexxmark** [comment]
@GitMensch Are you talking about winflexbison3? I think the regular winflexbison2 last version has XP support.

Someone who will need XP support will help us determine exact winflexbison3 version supporting XP then. I hope no one  needed XP support anymore.

**Comment by GitMensch** [comment]
> I think the regular winflexbison2 last version has XP support.

I've tested that. Yes, winflexbison2 last version works, [winflexbison 2.5.22 (bison 3.5.0, flex 2.6.4)](https://github.com/lexxmark/winflexbison/releases/tag/v2.5.22) is the most current one that works, from 2.5.23 I see the same failures as here.

... this _does_ make me wonder: what has changed in between?

**Comment by lexxmark** [comment]
>  this does make me wonder: what has changed in between?

My guess is that I just started to create releases by new version of Visual Studio which doesn't support XP any more.
