### ISSUE TITLE
Crash on invalid input

### ISSUE THREAD

**Issue by lexxmark** [lexxmark/winflexbison#64]
From sourceforge:

[rpcalc___win_bison_2.5.23_crash.zip](https://github.com/lexxmark/winflexbison/files/5362277/rpcalc___win_bison_2.5.23_crash.zip)

The attached file is the first example in chapter 2 of the Bison manual with minor changes including at least one typo. Bison crashes while processing the file. I did not look that closely at the cause of the crash except to see that a NULL pointer was being accessed when it appeared that several functions were exiting. The win_bison program was invoked with no arguments besides the name of the file. The latest released version of win_bison, 2.5.23, was being used.

**Comment by GitMensch** [comment]
Do you investigate that (if yes adding the assignment here would be good)?
Do you know already if this is an upstream bug or not? if it is then it _may_ be fixed in the development tree already (so we could pull that change), if it isn't fixed yet we should create bug report (much better: one including a patch).

**Comment by lexxmark** [comment]
I didn't investigate it yet. Going to look at all accumulated stuff later this week or next week.

**Comment by lexxmark** [comment]
I reproduced a crash and reported issue to GNU Bison project https://github.com/akimd/bison/issues/54
I don't have linux to try it by myself.

**Comment by lexxmark** [comment]
The upstream _bison_ project doesn't have such issue, I have outdated gnu lib source files.

I will update them next time I upgrade winflexbison.

**Comment by lexxmark** [comment]
this doesn't crash a new version https://github.com/lexxmark/winflexbison/files/5727962/win_flex_bison-2.5.24.zip

**Comment by lexxmark** [comment]
fixed in v2.5.24

**Comment by Croydon** [comment]
HI @lexxmark 

I think you can close https://sourceforge.net/p/winflexbison/tickets/11/ then too
