### ISSUE TITLE
Copy the first part of user declarations not into y.tab.h?

### ISSUE THREAD

**Issue by Nvocmoc** [lexxmark/winflexbison#7]
If I declare a YYSTYPE type like char*, it is copied into *y.tab.c*, which would make YYSTYPE default to int in *yy.tab.h*. This caused some memory errors when compiled with visual studio cl.exe. Problem was solved when I manually copied YYSTYPE declaration into *y.tab.h* before *typedef int YYSTYPE*.

**Comment by lexxmark** [comment]
Try

%code requires {
#define YYSTYPE char*
}

It should put this declaration in header file.
