### ISSUE TITLE
Missing LICENSE/COPYING file in repository toplevel

### ISSUE THREAD

**Issue by corco** [lexxmark/winflexbison#75]
The repository is missing a LICENSE or COPYING.

I believe flex is BSD and bison is GPLv3, which should make this project GPLv3 as it is the more restrictive license.

**Comment by GitMensch** [comment]
I was about to create COPYING GPLv3, but that would actually be wrong. This project is multi-licensed.

@AaronNGray You've specified GPLv3 back in SF, so if you don't say "no" I'll create a LICENSE file stating that the project (build scripts) is GPLv3 and add a COPYING in the root file (maybe have custom_build_rules/docs under FDL?) and also specify that the two main parts, bison and flex have their own licensing (possibly pointing to their COPYING file).

What do you think?

**Comment by GitMensch** [comment]
Ping @AaronNGray

**Comment by lexxmark** [comment]
@GitMensch Let's make the changes you proposed.

If @AaronNGray will complain we will discuss and implement other possible solutions.

**Comment by GitMensch** [comment]
Sounds fine, @lexxmark #76 is yours to merge (so we at least had four eyes on this).
If anything is wrong we can adjust in that branch, if everything is fine we can also merge that to the 2.7 branch.

[BTW: I _guess_ the 3.4.1 branch can be deleted, please do so if that's true]

**Comment by AaronNGray** [comment]
@GitMensch @lexxmark You need to go by the actual Unix Flex and Bison releases. I think they are GPLv3 hence me choosing that.

**Comment by GitMensch** [comment]
Bison is GPLv3+ since years, Flex was never GPL'd (see [its  license](https://github.com/westes/flex/blob/master/COPYING)), but I'll add another note about those (so far we covered the build scripts and "own" documentation only).
