### ISSUE TITLE
Fixing compile-time warnings

### ISSUE THREAD

**Issue by andan342** [lexxmark/winflexbison#8]
We have updated to the latest version of **winflexbison** after switching to C++17. Good news is that there are no more `register` variables in the generated code. 

However, there are two new warnings in the generated code introduced by **winflexbison** version 2.6.3, which were not the case with version 2.5.37:

1. (*possible information loss*) In `yyuserAction()` argument `size_t yyrhslen` is used to to compute an argument to `yyfill()`, which is `int`. 

2. (*macro redefined*) Macro `yylex` is defined in lexer and then re-defined in parser (yes, we use an intermediate layer, hence
```
#define yylex core_yylex
```
in the scanner (no such declaration here with v.2.5.37), and
```
#define yylex   base_yylex
```
in the parser.

The second problem might be related to westes/flex#162, which is fixed there.

**Comment by lexxmark** [comment]
Thank you for reporting issues here.
As I see the 1st problem related with **win_bison** tool and the 2nd with **win_flex**.

I found **yyuserAction** name in \bison\data\glr.c file only. It's skeleton file to produce actual generator source code. I didn't modify it during migration to windows system. There is no newer version of GNU bison tool available. So if you want we can fix it by ourself, just give me a patch that fixes the code.

For the second warning I can upgrade win_flex from 2.6.3 to 2.6.4 and give you to test. If it fixes warnings I'll publish a new release.

Regards,
   Alex

**Comment by andan342** [comment]
PR #9 created, fixing the first warning.

**Comment by andan342** [comment]
@lexxmark , thanks merging the fix!

The other problem appears to be resolved - [Flex 2.6.4](https://github.com/westes/flex/releases):
> *** We honor user defined yy_* macros again. We are also more careful to not leak macro definitions into header files.

Would be nice to update **winflexbison** to 2.6.4 soon. WDYT?

**Comment by lexxmark** [comment]
I'm working on it.
Once it's done I'll issue an update.

Thank you

**Comment by lexxmark** [comment]
Please try upgrated win_flex.exe executable:
[win_flex.zip](https://github.com/lexxmark/winflexbison/files/1456623/win_flex.zip)

**Comment by andan342** [comment]
I just completed an extensive check. Works well now. Thanks a lot!

**Comment by lexxmark** [comment]
You are welcome!
I have upgraded download page on sourceforge web site.
