### ISSUE TITLE
Could this project build with gcc

### ISSUE THREAD

**Issue by lili2012** [lexxmark/winflexbison#81]
I saw
 if(NOT MSVC)
   message( FATAL_ERROR "Visual Studio Build supported only" )
endif()
in CMakeLists.txt. Is this project Windows only?

**Comment by GitMensch** [comment]
It is named winflexbison so I assume it is. Flex and Bison are well portable to other environments already so there seems to be no point in targeting other environments here - but I'd prefer if other free compilers are supported here, too.

**Comment by lili2012** [comment]
I see. Thanks!
